name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Create dev image
      run: make dev-env

    - name: Compile
      run: make compile

    - name: Check fmt and clippy
      run: make check
